Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -39,6 +39,7 @@ jobs:
           git fetch --all
           git submodule update --remote --merge --init --recursive
           ver="${{ github.ref_name }}"
+          echo "out=untitled-i18n-${ver:1}" >> $GITHUB_OUTPUT
           sed -i "s/project(UntitledI18N.*/project(UntitledI18N VERSION ${ver:1})/g" CMakeLists.txt
           (git add . && git commit -m "Automatically bump version" && git push origin HEAD:master) || echo "Nothing to commit"
       - name: Commit
@@ -49,7 +50,12 @@ jobs:
         shell: bash
         run: |
           rm -rf .git/
-          tar cfJ untitled-i18n.tar.xz . || echo "Might have failed"
+
+          mkdir "${{ steps.mod.outputs.out }}" || exit
+          mv * ${{ steps.mod.outputs.out }}/ || echo "Errors in move"
+          mv .* "${{ steps.mod.outputs.out }}" || echo "Errors in move"
+
+          tar cfJ ${{ steps.mod.outputs.out }}.tar.xz ${{ steps.mod.outputs.out }} || echo "Might have failed"
       - name: Create Release
         uses: softprops/action-gh-release@v2
         with:
@@ -58,5 +64,5 @@ jobs:
             More on what is done this month can be found on the latest newsletter entry: https://madladsquad.com/#monthly-newsletter
           draft: false
           prerelease: false
-          files: untitled-i18n.tar.xz
+          files: ${{ steps.mod.outputs.out }}.tar.xz
           generate_release_notes: false
